version: "3.8"

services:
  web:
    # If you wish to build the container uncomment build and comment image.
    # build: .
    image: realprojectsegfault/snooddit
    restart: always
    container_name: "snooddit"
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
